name: CI -> Deploy to EC2

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install dependencies
        run: npm ci

      # Remove or comment this section if no build step
      # - name: Build
      #   run: npm run build

      - name: Archive repo for deploy
        run: |
          zip -r release.zip . -x "node_modules/***" ".git/***" ".github/***" "dist/***" "README.md"

      - name: Prepare private key
        run: |
          echo "$SSH_PRIVATE_KEY" > ./deploy_key
          chmod 600 ./deploy_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload release to server via scp
        run: |
          scp -o StrictHostKeyChecking=no -i ./deploy_key -P ${{ secrets.SSH_PORT }} release.zip ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/release.zip
          
      - name: Deploy on the remote server (unzip, rsync, npm install, restart service)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}       # use ec2-user here
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            mkdir -p ${{ secrets.EC2_TARGET_DIR }}
            command -v unzip >/dev/null 2>&1 || (echo "unzip not found; please install on server" && exit 1)
            command -v rsync >/dev/null 2>&1 || (echo "rsync not found; please install on server" && exit 1)

            unzip -o /tmp/release.zip -d /tmp/release
            rsync -av --delete /tmp/release/ ${{ secrets.EC2_TARGET_DIR }}/

            cd ${{ secrets.EC2_TARGET_DIR }}
            npm ci --production

            # restart systemd service (ec2-user has sudo)
            sudo systemctl daemon-reload || true
            sudo systemctl restart my-node-app.service
            sudo systemctl status my-node-app.service --no-pager